Editor/NDMFVRMExporter.cs

Set the position and rotation of the exported VRM root node to zero.
Currently, the transform information of the root node is copied as is. However, in VRM, anything other than scale is unnecessary and may even cause unintended issues. Additionally, since handling multiple avatars was not taken into account, at the very least, the position must be set to zero. There is essentially no reason to retain rotation in the root node, and the disadvantages outweigh the benefits, so it will also be set to zero. Scale, on the other hand, is needed in certain situations, so it will not be set to zero and will be retained.

[exporter] The root transform should be at origin and rotation identity

---

Editor/NDMFVRMExporter.cs

This fixes a bug where the culling mode setting was not correctly applied when using lilToon.
The built-in `_CullMode` property is set using an int type, whereas lilToon uses a float type, which caused an issue where [`Material.GetInt`](https://docs.unity3d.com/2022.3/Documentation/ScriptReference/Material.GetInt.html) could not retrieve the value correctly.
To address this, the culling mode will be included using the `ExportOverrides` mechanism, and the value will be pre-fetched using [`Material.GetFloat`](https://docs.unity3d.com/2022.3/Documentation/ScriptReference/Material.GetFloat.html), then converted to an int type and overwritten accordingly.

[exporter] fixes a bug `_CullMode` cannot retrieve properly on lilToon

---

Editor/NDMFVRMExporter.cs
README.md

This fixes a bug where `aimAxis` was being output as an empty string.
A new function is added to check the values of `aimAxis` or `AimVector` property and return a corresponding value for VRM. However, since VRM requires a fixed axis by specification, if the axis is not fixed, the value will not be converted. Instead, a warning will be issued, and it will be treated as if it does not exist.

[exporter] fixes a bug `aixAxis` is not set properly

---

README.md

Changes link of `vcc://` to https://hkrn.github.io/vpm.html
Fixes #6

[chore] change link `vcc://` to https://hkrn.github.io/vpm.html

---

CHANGELOG.md
Editor/NDMFVRMExporter.cs
package.json

This PR fixes a bug #4 is not actually fixed
Initially, I intended to fix this in #4, but the shader property that needed to be checked was different. After reviewing lilToon's implementation, it turned out that `_Cull` should be used instead. This has been corrected accordingly.
Since the fix in version 1.0.1 introduced another bug, I'll be releasing an urgent update.

[exporter] fixes a bug #4 is not actually fixed

---

Editor/NDMFVRMExporter.cs
Editor/Resources.meta
Editor/Resources/MetalGlossChannelSwap.shader
Editor/Resources/MetalGlossChannelSwap.shader.meta
Editor/Resources/MetalGlossOcclusionChannelSwap.shader
Editor/Resources/MetalGlossOcclusionChannelSwap.shader.meta
Editor/Resources/NormalChannel.shader
Editor/Resources/NormalChannel.shader.meta
Editor/Resources/README.md
Editor/Resources/README.md.meta

This PR  overhauls of texture processing
Initially, to reduce texture size, RGBA32 was used when an alpha channel was needed, while RGB24 was used when it was not. However, the added complexity outweighed the benefits, so all texture output has been unified to RGBA32. According to the glTF specification, unused channels are simply ignored, so this change does not cause any issues.
Previously, normal maps, metallic roughness textures, and occlusion textures were stored as is, without addressing the differences in storage methods between Unity and glTF. This has been corrected to match glTF’s format using the same approach as UnityGLTF.

[export] overhaul of texture processing

---

.github/workflows/gameci.yml

This PR allows to use `pull_request_target` except `.github` directory.
This is implemented to address the issue where the CI for #14 cannot be executed.

[CI] allow to use `pull_request_target` except `.github`

---

Editor/Document.cs

1. `componentType` が `UnsignedByte` の場合、`byteArray.Write()`で書き込むインデックスを `BitConverter.GetBytes((byte)index)` から `(byte)index` に変更し、1 バイトのデータが正しく書き込まれるように修正しました。  
2. `componentType` の判定基準を、`builder.BaseAccessorCount` ではなく、実際に使われているインデックス配列（`indices`）の最大値に基づいて決定するように変更しました。
- 従来のコードでは、`BitConverter.GetBytes((byte)index)` が 2 バイトの配列を返していたため、BlendShape の頂点インデックスが正しく読み取れず、BlendShape の変形が崩れる問題が発生していました。1 バイトで書き込む処理に変更することで、不具合を解消します。  
- 従来のコードでは、 `builder.BaseAccessorCount` に基づいて `componentType` を判定していました。しかし実際には、`BuildMorphTarget()`で`CreateSparseAccessorVector3()`に渡される頂点インデックス (`positions`) は、「BlendShape で変位が 0 (すなわち頂点が変形しない)」と判断されたインデックスが除外されているため、インデックスの最大値が `builder.BaseAccessorCount` と一致しないケースが存在します。実際のインデックス値（`indices` の最大値）を元に判定することが正しいと判断しました。

BlendShape の変形が正しく行われない問題を修正

---

.github/workflows/gameci.yml
Editor/Document.cs
Tests/Editor/GltfDocumentTest.cs

The PR fixes a bug where `WriteStream` was called twice.
During the process of adding unit tests, a bug was discovered where` WriteStream` was being called twice within `Exporter.CreateSampledTexture`. The issue occurred because `Exporter.CreateTextureSource`, which is called internally, had already written the necessary data. As a result, the subsequent `WriteStream` call wrote unused data, unnecessarily increasing the VRM file size.
This problem arose because `GltfDocumentTest.ExporterCreateSampledTexture` was not verifying the actual written data size. A new test has been added to ensure that the data size matches expectations. While the reduction depends on texture size, this change is expected to reduce VRM file size by up to nearly half.
Additionally, since the related PR #14 has …

[exporter] fix a bug where `WriteStream` was called twice

---

Editor/NDMFVRMExporter.cs

This PR fixes an issue where multiple PB colliders were not considered
Previously, cases where a single game object contained multiple PB colliders were not accounted for. This is necessary, for example, when combining multiple sphere colliders to approximate a capsule collider. This update adds support for such cases.
While, in principle, multiple PBs and constraints could also be supported, this commit does not address that.

[exporter] fix issue where multiple PB colliders were not considered

---

Editor/NDMFVRMExporter.cs

This PR uses `Graphics.ConvertTexture` instead of `Graphics.CopyTexture`.
It was discovered that `Graphics.CopyTexture` does not always work as expected on Windows. Testing confirmed that using `Graphics.ConvertTexture` produces the expected results, so the conversion method has been updated accordingly.

[exporter] use `Graphics.ConvertTexture` instead

---

Editor/NDMFVRMExporter.cs
README.md

This PR processes PB branches as independent segments.
Previously, PB branches were not considered, resulting in a single continuous chain being exported as a Spring Bone. With this fix, branches are now handled separately, and when a split occurs, each branch is processed independently. However, since VRM does not define behavior for branched Spring Bones and relies on implementation specifics, this will be explicitly noted in the README.

[exporter] process PB branches as independent segments

---

package.json

This PR changes NDMF compatible version to 1.6 or higher but less than 2.0
We are making the above change because the current version specification may prevent compatibility with NDMF 1.7 or higher, which is expected to be released soon.

[exporter] Change NDMF compatible version to 1.6 or higher but less than 2.0

---

Editor/Localization/en-us.po
Editor/NDMFVRMExporter.cs
README.md

This PR adds vertex index corruption detection processing.
As a countermeasure for GH-38, we will add a process to check that the index references are correct in the Skinned Mesh Renderer corruption detection. We will also make improvements to enable corruption detection for multiple Skinned Mesh Renderers.

[exporter] Add vertex index corruption detection processing

---

Editor/NDMFVRMExporter.cs
README.md

This PR fixes a bug where source joints were included when `Multi-Child Type` was set to `Ignore`.
(none)

[exporter] Fixes a bug where source joints were included when `Multi-Child Type` was set to `Ignore`

---

Editor/Document.cs

This PR suppresses ReSharper warnings.
We will also change some classes to static classes to address ReSharper warnings. While there is compatibility at the source code level, it may break at the binary level. (Note that these were not originally intended to be used directly from external sources).

[exporter] Suppress ReSharper warnings

---

Editor/NDMFVRMExporter.cs

This PR fixes a bug where emission textures were not being output when using lilToon.
The bug was occurring due to the commit for GH-23.

[exporter] Fixed a bug where emission textures were not being output when using lilToon

---

Editor/Localization/en-us.po
Editor/NDMFVRMExporter.cs

This PR adds output of information in NDMF dialog when ShadingToony is `NaN`
Implemented as an emergency measure for GH-47. While this doesn't prevent VRM output itself as it's a valid glTF, it provides information that the file may not be loadable as a VRM.
The permanent solution depends on the response to https://github.com/lilxyzw/lilToon/issues/263

[exporter] Added output of information in NDMF dialog when ShadingToony is `NaN`

---

Editor/Localization/en-us.po
Editor/NDMFVRMExporter.cs

This PR fixes multiple bugs in material output. Relates #55
This commit fixes a bug where `IndexOutOfRangeException` occurs when the number of submeshes is greater than the number of materials. In such cases, `sharedMaterial` result is applied to out-of-range submeshes, and information is output to the NDMF console.
I also confirmed that there is an issue where `TryGetValue` throws an exception when the material is `None`, so in such cases, information will be output to the NDMF console on a per-mesh basis and the processing will be skipped.

[exporter] Fixes multiple bugs in material output

---

Editor/Localization/en-us.po
Editor/NDMFVRMExporter.cs

This PR remove workaround for `ShadeToony` becoming `NaN`.
Applied the same conversion formula since a fix commit was made on the lilToon side
https://github.com/lilxyzw/lilToon/commit/0648caedc9e70a9da946a56d31efe693c7b632bb
Since the above prevents `NaN` from occurring, the workaround has been removed.

[exporter] Remove workaround for `ShadeToony` becoming `NaN`

---

Editor/NDMFVRMExporter.cs

This PR fixes a bug where MeshRenderer conversion fails with NRE.
Fixed a bug where NullReferenceException occurs when converting MeshRenderer due to a variable typo.

[exporter] Fixed a bug where MeshRenderer conversion fails with NRE

---

Editor/NDMFVRMExporter.asmdef

This PR removes the upper limit from version constraints in asmdef
I plan to change this if completely incompatible changes occur, but this addresses the issue where the current version constraints cause everything to become Standard shader and prevent lilToon conversion due to the recent release of lilToon 2.x. While lilToon 2.x has removed unused features, this has no impact since NDMF VRM Exporter does not support conversion for those.

[asmdef] removes upper version constraint

---

Editor/NDMFVRMExporter.cs

This PR applies stricter mesh corruption processing.
Previously, corruption detection was performed only by null checking the bone array, but there was an issue of false positives where bones filled with null values appeared as unreferenced even when they were actually being used. To align with the actual processing, this has been modified to check for null by examining references from the mesh's `boneWeights`.
Relates GH-40

[exporter] Stricter mesh corruption processing
