Editor/NDMFVRMExporter.cs

This addresses an issue where hidden joints and constraint source nodes are referenced in `_transformNodeIDs`, causing a `KeyNotFoundException`.
The cause of the issue is as described above. To address it, a newly introduced method, `FindTransformNodeID`, will be added and used for checking. Additionally, if a node is not found, a warning will be logged to the console using `Debug.LogWarning`.

[exporter] Inactive joint/constraint source transform should not be referred

---

README.md

Updates README.md
Add supplementary information on how to set up and verify the exported VRM.

[readme] adds getting started and note for viewing exported VRM

---

CHANGELOG.md
README.md

Adds `CHANGELOG.md`.
Add a `CHANGELOG.md` in the [Keep a Changelog](https://keepachangelog.com) format. Additionally, fix a bug where the repository link in the README was not working.

[docs] adds CHANGELOG.md

---

CHANGELOG.md
package.json

Prepares `1.0.1` package
(none)

[release] `1.0.1`

---

.github/workflows/release.yml

This PR removes directories that should be includes into package, and adds printing SHA256 checksum with `sha256sum` for `vpm.json`.
(none)

[CI] removes directories that should be includes into package

---

Editor/NDMFVRMExporter.cs

This PR fixes a bug baking shadow texture doesn't perform properly.
(same as commit log)
The issue was caused by attempting to extract and bake a null texture from `_bakedMaterialMainTextures`. As a result, the main texture that should have been assigned to the shadow texture was missing during the baking process. This led to the generation of a 2x2 white shadow texture, causing shadows to be incorrectly rendered in MToon.
To fix this, `_bakedMaterialMainTextures` has been modified to always contain the main texture.
Additionally, the information from `gltf.material.TextureInfo` is now stored to prevent redundant processing by `ExportTextureInfoMToon`.

[exporter] fixes a bug baking shadow texture does't work properly

---

CHANGELOG.md
package.json

Prepares `1.0.3` package
(none)

[release] `1.0.3`

---

Tests/Editor/GltfDocumentTest.cs
Tests/Editor/VrmCoreTest.cs
Tests/Editor/VrmMToonTest.cs

This PR renames several incorrect test method names.
(none)

[chore] renames several incorrect test method names

---

Editor/NDMFVRMExporter.cs

This PR disables emission when an emission mask is present in lilToon
When lilToon's emission is enabled and an emission mask is present, the emission should be restricted according to the mask. However, since MToon does not support this functionality, the material emits light regardless of the emission mask, causing an issue.
Additionally, since lilToon does not have an implementation for baking emission separately, emission will be uniformly disabled when an emission mask is present.

[exporter] disable emission when an emission mask is present in lilToon

---

Editor/NDMFVRMExporter.cs
README.md

This PR modifies constraint output based on `Freeze Rotation Axis`.
This implementation is made to align with #11.

[exporter] modify constraint output based on `Freeze Rotation Axis`

---

Editor/NDMFVRMExporter.cs

This PR introduces comprehensive overhaul of texture handling and baking.
`MaterialBaker.SetMaterialTexture` has been split into `MaterialBaker.AssignMaterialTexture` and `MaterialBaker.LoadTexture`, with the main processing consolidated into `MaterialBaker.LoadTexture`.
Additionally, if a texture can be loaded, it is now first encoded as a PNG and then reloaded to reduce the likelihood of texture baking failures.
Furthermore, a new `MToonTexture` has been introduced to improve flexibility and maintainability.

[exporter] comprehensive overhaul of texture handling and baking

---

CHANGELOG.md
package.json

This PR prepares `1.0.5` package
(none)

[release] `1.0.5`

---

Editor/NDMFVRMExporter.cs

This PR does class-based refactoring for KTX texture generation.
The processing previously consolidated in `ConvertAllTexturesToKtx` has been separated into a builder class and a conversion class, which are now used for execution.
Additionally, the implementation has been modified to use standard input and output, eliminating the need for temporary intermediate files.

[exporter] class-based refactoring for KTX texture generation

---

Editor/NDMFVRMExporter.cs

This PR fixes an issue here root bone was missing from VRM spring bone.
It was discovered that the root bone of the spring bone was not included in the chain of the exported VRM's spring bone. This update fixes that issue.
Additionally, an issue where the depth was not correctly obtained when the chain branched midway has also been addressed.

[exporter] fix an issue here root bone was missing from VRM spring bone

---

README.md

This PR fixes `TIP` typo and clarification.
(none)

[readme] fixes `TIP` and clarification

---

Editor/NDMFVRMExporter.cs

This PR supports for converting multiple PB components.
This was previously deferred in commit 80ed4b73ae9130f0003c7096edc49ed3629a37c1, but since the README now explicitly states that multiple constraint support will not be converted, the implementation has been revisited and added.

[exporter] support for converting multiple PB components

---

CHANGELOG.md
package.json

This PR prepares `1.0.6` package
(none)

[release] `1.0.6`

---

.editorconfig

This PR adds `.editorconfig` ([EditorConfig](https://editorconfig.org))
(none)

[chore] adds `.editorconfig`

---

Editor/NDMFVRMExporter.cs

This PR changes to use `GetValueOrDefault` for retrieving a value from lilToon's properties.
This addresses GH-51 (the issue of exceptions occurring when necessary material properties cannot be found). Also, since the types are all determined, changed to reduce the effort of extracting with `ToDictionary` and calling `floatValue` and `colorValue`.

[exporter] Changed to use `GetValueOrDefault`

---

CHANGELOG.md
package.json

This PR prepares `1.0.9` package
(none)

[release] `1.0.9`

---

README.md

This PR adds design philosophy and FAQ.
(None)

[readme] Adds design philosophy and FAQ

---

CHANGELOG.md
package.json

This PR prepares 1.0.12 package
(none)

[release] `1.0.12`

---

CHANGELOG.md
package.json

This PR prepares 1.0.13 package
(none)

[release] `1.0.13`

---

CHANGELOG.md
package.json

This PR prepares 1.0.14 package.
(none)

[release] `1.0.14`

---

CHANGELOG.md
package.json

This PR prepares 1.0.15 package.
(none)

[release] `1.0.15`
